### ISSUE TITLE
License under MIT or Apache 2.0 license

### ISSUE THREAD

**Issue by TheButlah** [isouriadakis/Arduino_ICM20948_DMP_Full-Function#3]
Hi,

No license is specified here, which means our MIT licensed project cannot use it. Can you license it? What about the code it was derived from?

**Comment by isouriadakis** [comment]
This library is based on the Invensense provided eDM, therefore is up to the license provided by InvenSense to use the library with your product. In terms of the code I have written, you can use it as it is.

If it helps I can license my part of the code.

**Comment by TheButlah** [comment]
Giving it a full MIT license might be misleading or invalid since the source its derived from is not open source. Not totally sure how this is handled legally.

I think its enough to say that I can't really use this library ;(
