### ISSUE TITLE
Save DMP calibration data 

### ISSUE THREAD

**Issue by mpnvdlee** [isouriadakis/Arduino_ICM20948_DMP_Full-Function#5]
Is it possible to save the DMP self-calibration data and restore it at start-up with this library?
This way you don’t have to wait and move the IMU for about 30s before using it.

Thanks for the great library anyway!

**Comment by isouriadakis** [comment]
Hi, based on the datasheet it should be possible, but is not integrated in this library. You basically need to access some registers where the offsets are saved and then load them back at startup

**Comment by mpnvdlee** [comment]
Allright! Thanks for the quick reply.

Unfortunately I am not experienced enough to add this functionality myself (quite new in Arduino libraries).
Maybe a nice addition for this library in the future then!
