### ISSUE TITLE
How to actually use the library?

### ISSUE THREAD

**Issue by joshgalvan** [isouriadakis/Arduino_ICM20948_DMP_Full-Function#6]
Is the library on the Arduino Library manager? I'm unable to just copy the library into my Arduino folder and reference any of the code for some reason.

**Comment by joshgalvan** [comment]
I am able to copy and paste the source files into my sketch directory as long as there is no nested folder, it's just all source files at the same level as the sketch (which seems to be an Arduino IDE limitation), but I feel like a way to use the library should be documented.

**Comment by KiwiHuman** [comment]
how were you able to solve this? I am having the same issue.
